### ISSUE TITLE
Geocoding doesn't work anymore since version 7.4

### ISSUE THREAD

**Issue by Ajojo44** [mapbox/mapbox-java#1044]
Hi all, 

I'd like to continue an issue than someone else started on the mapbox-jl-native repository: https://github.com/mapbox/mapbox-gl-native/issues/14845

I've the same problem and the exception thrown is the following one:
```
java.lang.IllegalStateException: Not a JSON Array: {"type":"Point","coordinates":[1.516222,47.882982]}
        at x.x.x.geocoding.MapboxGeocodingProvider$searchForDestination$$inlined$suspendCancellableCoroutine$lambda$1.onFailure(MapboxGeocodingProvider.kt:56)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:80)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

Everytime I perform a geocoding request, I got this error if the request leads to results. If no result is found for the request, then I get a correct response without exception.

This only happens in version 7.4 and 8.0. I don't have the exception in version 7.3.2. I switched multiple times between these versions and this is verified as not working only since v7.4.

Here is the implementation of my geocoding part:

```kotlin
suspendCancellableCoroutine<List<SearchSuggestion>> { continuation ->
    val proximity = Point.fromLngLat(location.longitude, location.latitude)
    val locale: Locale = LocaleListCompat.getDefault()[0]

    val request = MapboxGeocoding.builder()
        .autocomplete(true)
        .accessToken(accessToken)
        .geocodingTypes(TYPE_PLACE, TYPE_ADDRESS, TYPE_POI)
        .limit(MAX_NUMBER_OF_SUGGESTIONS)
        .proximity(proximity)
        .languages(locale)
        .query(search)
        .country(ACCEPTED_COUNTRIES)
        .build()

    continuation.invokeOnCancellation {
        request.cancelCall()
    }

    request.enqueueCall(object : Callback<GeocodingResponse> {
            override fun onFailure(call: Call<GeocodingResponse>, t: Throwable) {
                continuation.resumeWithException(t)
            }

            override fun onResponse(call: Call<GeocodingResponse>, response: Response<GeocodingResponse>) {
                // Check if request is a success
                if (!response.isSuccessful) {
                    if (response.code() == INVALID_TOKEN_HTTP_CODE) {
                        continuation.resumeWithException(MapboxTokenExpiredException("Token invalid while performing geocoding"))
                        return
                    }

                    continuation.resumeWithException(SearchImpossibleException("response not successful - code=${response.code()} ; message=${response.message()}"))
                    return
                }

                val suggestions =  [...]

                continuation.resume(suggestions)
            }
    })
}
```

**Comment by spiekermax** [comment]
Thank you for opening this issue on the right repository for me! I can confirm everything regarding your description of the issue.

**Comment by tobrun** [comment]
cc @langsmith @zugaldia

**Comment by zugaldia** [comment]
Possibly related: https://github.com/mapbox/mapbox-plugins-android/issues/976.

@langsmith I know that you've been looking at this part of the code recently in the context of https://github.com/mapbox/mapbox-plugins-android/pull/968. Could you research what might be happening here when you have a chance?

**Comment by langsmith** [comment]
Yes, I will look into this.

**Comment by langsmith** [comment]
Hey @Ajojo44 , thanks for using Mapbox.

What version of `mapbox-sdk-services` are you using?

**Comment by langsmith** [comment]
I set up a completely new Android app following https://www.mapbox.com/install/android/. Then I added the following dependencies:

```groovy
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.0'
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.8.0'
```

Then I added the following inside of the `onStyleLoaded()` callback.

```java
findViewById(R.id.make_geocoding_call_button).setOnClickListener(new View.OnClickListener() {
              @Override
              public void onClick(View view) {
              
                MapboxGeocoding mapboxGeocoding = MapboxGeocoding.builder()
                  .accessToken(ACCESS_TOKEN)
                  .query("1600 Pennsylvania Ave NW")
                  .autocomplete(true)
//                  .geocodingTypes(TYPE_PLACE)
                  .limit(10)
                  .build();

                mapboxGeocoding.enqueueCall(new Callback<GeocodingResponse>() {
                  @Override
                  public void onResponse(Call<GeocodingResponse> call, Response<GeocodingResponse> response) {

                    List<CarmenFeature> results = response.body().features();

                    if (results.size() > 0) {

                      // Log the first results Point.
                      Point firstResultPoint = results.get(0).center();
                      Log.d(TAG, "onResponse: firstResultPoint.toString() = " + firstResultPoint.toString());
                      Log.d(TAG, "onResponse: results.get(0).toString() = " + results.get(0).toString());

                    } else {

                      // No result for your request were found.
                      Log.d(TAG, "onResponse: No result found");

                    }
                  }

                  @Override
                  public void onFailure(Call<GeocodingResponse> call, Throwable throwable) {
                    throwable.printStackTrace();
                    Log.d(TAG, "onFailure:");

                  }
                });
                
              }
});
```

The dependency setup listed at the top of this comment gave me the same `IllegalStateException` as shown in OP's ticket.

![Screen Shot 2019-06-10 at 3 49 50 PM](https://user-images.githubusercontent.com/4394910/59232399-04e6c300-8b99-11e9-982c-dc7dcd165f3b.png)

Switching to the `4.9.0-SNAPSHOT`, got a `MapboxGeocoding` call to work fine for me. 

```groovy
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.0'
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.9.0-SNAPSHOT'
```

![Screen Shot 2019-06-10 at 4 07 50 PM](https://user-images.githubusercontent.com/4394910/59232608-f6e57200-8b99-11e9-9d45-c0fed75be6a1.png)

```
2019-06-10 16:07:45.047 13220-13220/com.mapbox.myapplication D/MainActivity: onResponse: firstResultPoint.toString() = Point{type=Point, bbox=null, coordinates=[-77.036547, 38.897675]}
2019-06-10 16:07:45.048 13220-13220/com.mapbox.myapplication D/MainActivity: onResponse: results.get(0).toString() = CarmenFeature{type=Feature, bbox=null, id=address.1483398214483284, geometry=Point{type=Point, bbox=null, coordinates=[-77.036547, 38.897675]}, properties={"accuracy":"rooftop"}, text=Pennsylvania Avenue Northwest, placeName=1600 Pennsylvania Avenue Northwest, Washington, District of Columbia 20500, United States, placeType=[address], address=1600, rawCenter=[-77.036547, 38.897675], context=[CarmenContext{id=neighborhood.291451, text=Downtown, shortCode=null, wikidata=null, category=null, maki=null}, CarmenContext{id=postcode.1483398214483284, text=20500, shortCode=null, wikidata=null, category=null, maki=null}, CarmenContext{id=place.7673410831246050, text=Washington, shortCode=null, wikidata=Q61, category=null, maki=null}, CarmenContext{id=region.1753213251667470, text=District of Columbia, shortCode=US-DC, wikidata=Q3551781, category=null, maki=null}, CarmenContext{id=country.9053006287256050, text=United States, shortCode=us, wikidata=Q30, category=null, maki=null}], relevance=1.0, matchingText=null, matchingPlaceName=null, language=null}
```

I think the `IllegalStateException` issue is about `Feature` serialization, which was probably addressed by https://github.com/mapbox/mapbox-java/pull/1034. #1034 was added to `master` 24 days ago, but [the latest Java SDK release was 28 days ago](https://github.com/mapbox/mapbox-java/releases). That's why the `SNAPSHOT` works. Could be time for us to release a new stable version of this SDK?

What's weird is that when I switched back to `4.8.0` from the `4.9.0-SNAPSHOT`, the geocoding call started worked for me. I uninstalled this dummy app from my phone, `invalidate cache & restart` via Android Studio, etc. Geocoding also worked on `4.7.0` and `4.6.0`. Anyways, all of this is why I ask which version of  `mapbox-sdk-services` you're using @Ajojo44.

**Comment by Ajojo44** [comment]
I don't use mapbox-sdk-service library, just mapbox-android-sdk and the com.mapbox.mapboxsdk:mapbox-android-plugin-places-v7. For the places plugin, I use version 0.8.0 which integrates mapbox-sdk-services:4.3.0. Should I add mapbox-sdk-services with newer version to override it?

**Comment by Ajojo44** [comment]
Ok, removing `mapbox-android-plugin-places-v7` and using the `mapbox-sdk-services:4.3.0` solved the problem for me.

**Comment by langsmith** [comment]
Ok, glad you got it working @Ajojo44 .
