### ISSUE TITLE
Crashes trying to parse DirectionsRoute json

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-java#1274]
This new function will crash when the routeOptions contains an accessToken

Noticed after trying to rebase on this one https://github.com/mapbox/mapbox-navigation-android/pull/4526
https://github.com/mapbox/mapbox-java/pull/1270

``` kotlin
  public static DirectionsRoute fromJson(@NonNull String json) {
    GsonBuilder gson = new GsonBuilder();
    JsonObject jsonObject = gson.create().fromJson(json, JsonObject.class);
    if (jsonObject.has("routeOptions")) {
      throw new IllegalArgumentException(
        "Provided serialized route contains RouteOptions. "
          + "Use DirectionsRoute#fromJson(json, accessToken) instead."
      );
    }
    gson.registerTypeAdapterFactory(DirectionsAdapterFactory.create());
    gson.registerTypeAdapter(Point.class, new PointAsCoordinatesTypeAdapter());
    return gson.create().fromJson(jsonObject, DirectionsRoute.class);
  }
```

Also if we use `DirectionsRoute.fromJson(directions, accessToken)`

It will crash because the coordinates have been removed

``` kotlin
  public static DirectionsRoute fromJson(@NonNull String json, @NonNull String accessToken) {
    GsonBuilder gson = new GsonBuilder();
    JsonObject jsonObject = gson.create().fromJson(json, JsonObject.class);
    if (jsonObject.has("routeOptions")) {
      JsonObject routeOptions = jsonObject.getAsJsonObject("routeOptions");
      routeOptions.addProperty("access_token", accessToken);
    } else {
      throw new IllegalArgumentException(
        "Provided serialized route does not contain RouteOptions. "
          + "Use DirectionsRoute#fromJson(json) instead."
      );
    }
    gson.registerTypeAdapterFactory(DirectionsAdapterFactory.create());
    gson.registerTypeAdapter(Point.class, new PointAsCoordinatesTypeAdapter());
    return gson.create().fromJson(jsonObject, DirectionsRoute.class);
  }
```

```
2021-07-21 10:46:21.160 14054-14054/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 14054
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.routeOptions.coordinates
        at com.google.gson.Gson.fromJson(Gson.java:944)
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.Gson.fromJson(Gson.java:975)
```

cc: @LukasPaczos  @korshaknn

**Comment by kmadsen** [comment]
This API seems broken because `DirectionsRoute.toJson` will create a json that is including `RouteOptions`.

But then the `DirectionsRoute.fromJson` will crash when it has route options

**Comment by kmadsen** [comment]
"coordinates":[[-122.5237429,37.975393],[-122.5231413,37.9750695]]

"coordinates":"-122.5237429,37.975393;-122.5231413,37.9750695"

it seems the new json parser requires this change to coordinates 🤔

**Comment by kmadsen** [comment]
These are all the issues you will see when attempting to use 

`DirectionsRoute.toJson` in a previous version. saving the data in a file (or persisting in your app's disk)
`DirectionsRoute.fromJson` in a new version

These are known issues

**Comment by kmadsen** [comment]
To update your json files. Update the routeOptions coordinates

```
- "coordinates":[[-122.5237429,37.975393],[-122.5231413,37.9750695]]
+ "coordinates":"-122.5237429,37.975393;-122.5231413,37.9750695"
```

**Comment by LukasPaczos** [comment]
I'm going to append the example fix to the existing changelog entry for this so that everyone has an easier time discovering how to resolve the breaking change.
