### ISSUE TITLE
`RouteOptions::toUrl` doesn't encode '&' character in query parameters

### ISSUE THREAD

**Issue by tomaszrybakiewicz** [mapbox/mapbox-java#1409]
### Description

One of our customers detected a crash caused by requesting routes with waypoint names containing '&' character. From the captured crash log we determined the root cause of the crash to be incorrect `waypoint_names` argument encoding by the `RouteOptions::toUrl` method.

```
DIRECTIONS_API?access_token=<token>&geometries=polyline6&alternatives=true&overview=full&steps=true&avoid_maneuver_radius=111.11111450195312&bearings=13.6232796,90;&layers=0;&continue_straight=true&annotations=distance,congestion,maxspeed&language=en_SG&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=metric&waypoints=0;1&waypoint_names=;Serangoon%20Garden%20Market%20&%20Food%20Centre&enable_refresh=true
```

### Crash details

Investigation and support ticket: https://github.com/mapbox/ask-navigation/issues/94

**Configuration:**
Operating systems + versions: Android 11
Device/simulator/emulator models: Samsung Galaxy Note20 Ultra 5G

**Steps to reproduce**
1. set a destination that contains & in the name of destination

```kotlin
val waypointNamesList=listof("","Serangoon Garden Market & Food Centre")
var routeOptionsBuilder = RouteOptions.builder()
....
routeOptionsBuilder.waypointNamesList(waypointNamesList)
routeOptionsBuilder.build()
```

2. make reroute happen

**Captured Crash log:**
```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
       at java.lang.String.substring(String.java:2064)
       at com.mapbox.api.directions.v5.models.RouteOptions.fromUrl(RouteOptions.java:883)
       at com.mapbox.navigation.base.route.NavigationRoute$Companion.create(NavigationRoute.java:71)
       at com.mapbox.navigation.base.internal.utils.DirectionsResponseUtilsKt$parseDirectionsResponse$2.invokeSuspend(DirectionsResponseUtils.kt:19)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by jinny-nam** [comment]
hi @korshaknn I see the PR has been merged, but it seems that we are going to need a better solution? (based on your description on the PR)
On the other hand, the customer would like to have a patch for the fix, other than waiting for the next sdk release that includes the fix. Would it be a possible option? 
cc: @linsd75

**Comment by korshaknn** [comment]
@jinny-nam hey! yes, we are going to provide a patch. 
cc @LukasPaczos @zugaldia
