### ISSUE TITLE
Strictmode violation Telemetry startup

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#298]
When trying out the downstream PR on telem in https://github.com/mapbox/mapbox-gl-native/pull/7892, I noticed that we are still hitting strictmode violations related to telemetry. The following three entries are pointing to:

```
MapboxTelemetry.getInstance().initialize(appContext, accessToken, locationEngine);
``` 

> 01-31 12:25:40.986 31571-31571/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=48 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                                                                              at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                              at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                              at java.io.File.exists(File.java:780)
                                                                              at android.app.ContextImpl.getDataDir(ContextImpl.java:1938)
                                                                              at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:466)
                                                                              at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:627)
                                                                              at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:345)
                                                                              at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
                                                                              at com.mapbox.services.android.telemetry.utils.TelemetryUtils.getSharedPreferences(TelemetryUtils.java:42)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.loadUserPreferences(MapboxTelemetry.java:253)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:127)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:98)
                                                                              at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:40)
                                                                              at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                                              at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

> 01-31 12:25:40.986 31571-31571/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=47 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                                                                              at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                              at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
                                                                              at java.io.File.exists(File.java:780)
                                                                              at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:512)
                                                                              at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:468)
                                                                              at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:627)
                                                                              at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:345)
                                                                              at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
                                                                              at com.mapbox.services.android.telemetry.utils.TelemetryUtils.getSharedPreferences(TelemetryUtils.java:42)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.loadUserPreferences(MapboxTelemetry.java:253)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:127)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:98)
                                                                              at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:40)
                                                                              at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                                              at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

> 01-31 12:25:40.986 31571-31571/com.mapbox.mapboxsdk.testapp D/StrictMode: StrictMode policy violation; ~duration=45 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
                                                                              at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                              at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:203)
                                                                              at android.app.SharedPreferencesImpl.contains(SharedPreferencesImpl.java:270)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.loadUserPreferences(MapboxTelemetry.java:256)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:127)
                                                                              at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:98)
                                                                              at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:40)
                                                                              at com.mapbox.mapboxsdk.testapp.MapboxApplication.onCreate(MapboxApplication.java:40)
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                                              at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)\

cc @zugaldia

**Comment by tobrun** [comment]
FYI: the strictmode logs on downstream master are a bit more usefull as they directly point to this line:

```
    SharedPreferences prefs = context.getSharedPreferences(MapboxConstants.MAPBOX_SHARED_PREFERENCES_FILE,
      Context.MODE_PRIVATE);
```

and

```
setTelemetryEnabled(prefs.getBoolean(MapboxConstants.MAPBOX_SHARED_PREFERENCE_KEY_TELEMETRY_ENABLED, true));
```

**Comment by zugaldia** [comment]
Considering we're using `apply` now [it seems this is a smaller issue](http://stackoverflow.com/questions/4371273/should-accessing-sharedpreferences-be-done-off-the-ui-thread) though technically correct. Let's keep it open as we iterate the telemetry module.

**Comment by cammace** [comment]
@Guardiola31337 @electrostat can we close or move this ticket to the correct repo?
