### ISSUE TITLE
Change old locations services in favor of new LocationEngine abstraction

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#301]
Some activities which are using old locations services (`GeocodingWidgetActivity` and `GeocodingServiceActivity`) are crashing when calling `FusedLocationProviderService.requestLocationUpdates` or `FusedLocationProviderService.getLastLocation` methods.

> FATAL EXCEPTION: main
                                                                                     Process: com.mapbox.services.android.testapp, PID: 26935
                                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.services.android.testapp/com.mapbox.services.android.testapp.geocoding.GeocodingServiceActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.location.Location com.mapzen.android.lost.internal.FusedLocationProviderService.getLastLocation(com.mapzen.android.lost.api.LostApiClient)' on a null object reference
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.location.Location com.mapzen.android.lost.internal.FusedLocationProviderService.getLastLocation(com.mapzen.android.lost.api.LostApiClient)' on a null object reference
                                                                                         at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.getLastLocation(FusedLocationProviderApiImpl.java:100)
                                                                                         at com.mapbox.services.android.testapp.geocoding.GeocodingServiceActivity.getLastLocation(GeocodingServiceActivity.java:155)
                                                                                         at com.mapbox.services.android.testapp.geocoding.GeocodingServiceActivity.onStart(GeocodingServiceActivity.java:148)
                                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                                         at android.app.Activity.performStart(Activity.java:6253)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

Use new `LocationEngine` abstraction to fix those crashes.

**Comment by zugaldia** [comment]
@ghoshkaj Now that https://github.com/mapbox/mapbox-java/pull/300 has landed, these are the activities that remain unstable.

**Comment by Guardiola31337** [comment]
`4.x` -> `5.x` changes made:

- Add `onStart()`/`onStop()` methods calls
- Change `map.getMarkerViewManager().scheduleViewMarkerInvalidation()` -> `map.getMarkerViewManager().update()`
- Change `MapboxAccountManager.start()` -> `Mapbox.getInstance()`
- Change `MapboxAccountManager.getInstance().getAccessToken()` -> `Mapbox.getAccessToken()`
- Fix xml namespace:
  - `xmlns:mapbox` -> `xmlns:app`
  - `mapbox:center_latitude` -> `app:mapbox_cameraTargetLat`
  - `mapbox:center_longitude` -> `app:mapbox_cameraTargetLng`
  - `mapbox:style_url` -> `app:mapbox_styleUrl`
  - `mapbox:zoom` -> `app:mapbox_cameraZoom`
  - `mapbox:rotate_enabled` -> `app:mapbox_uiRotateGestures`
- Add `LocationEngine` abstraction and `MockLocationEngine`, `GoogleLocationEngine`, `LostLocationEngine` and `AndroidLocationEngine` implementations
- Add `LocationEngineListener`
