### ISSUE TITLE
Fix mock location engine crash

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#492]
If a route isn't provided to the mock location engine but you call `moveToLocation()` eventually the activity will crash with this in the log output:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.services.api.directions.v5.models.DirectionsRoute.getLegs()' on a null object reference
                                                                                          at com.mapbox.services.android.location.MockLocationEngine.calculateStepPoints(MockLocationEngine.java:304)
                                                                                          at com.mapbox.services.android.location.MockLocationEngine.access$200(MockLocationEngine.java:32)
                                                                                          at com.mapbox.services.android.location.MockLocationEngine$LocationUpdateRunnable.run(MockLocationEngine.java:357)
                                                                                          at android.os.Handler.handleCallback(Handler.java:769)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6535)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by cammace** [comment]
Should be fixed or will be fixed in the Navigation repo where the mock location engine will live from here on out.
