### ISSUE TITLE
Working fine on emulator but on physical devices it return on a null object reference

### ISSUE THREAD

**Issue by kims89** [mapbox/mapbox-java#53]
Hello, the API is working fine for me on emulators. But on the physical device, it crashes and return.
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.services.directions.v4.models.DirectionsResponse.getRoutes()' on a null object reference
                                                                           at net.fjos.distancefinder.MainActivity.finnDistanse(MainActivity.java:158)
                                                                           at net.fjos.distancefinder.MainActivity$1.onClick(MainActivity.java:101)
                                                                           at android.view.View.performClick(View.java:5204)
                                                                           at android.view.View$PerformClick.run(View.java:21155)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by zugaldia** [comment]
@kims89 thanks for the feedback. There should be no difference in behavior between the emulator and the device, this could be an error related to Internet connectivity.

Could you share the code that you use to launch the request?

**Comment by kims89** [comment]
Okey, think I found the problem. The default language on emulator is English, but on my device its Norwegian. Is it possible to fix it in some way? When I set language to English (brit), it work perfectly...

Thanks :)

**Comment by zugaldia** [comment]
@kims89 Glad to hear you figured this out! I'm afraid you hit https://github.com/mapbox/mapbox-java/issues/39.

This is now fixed and it'll be available in the next release. In the meanwhile, you can test it using the SNAPSHOT. You'd need to do this in your `build.gradle`:

```
repositories {
    mavenCentral()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile ('com.mapbox.mapboxsdk:mapbox-java-services:1.1.0-SNAPSHOT@jar'){
        transitive=true
    }
}
```

Closing now, feel free to reopen if the problem persists.
