### ISSUE TITLE
Crash handling error code for route not found

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#612]
Getting this crash with `3.0` when I try to retrieve a route that isn't possible (like across an ocean):

```
java.lang.NullPointerException: Null code
     at com.mapbox.directions.v5.models.$AutoValue_DirectionsError.<init>($AutoValue_DirectionsError.java:18)
     at com.mapbox.directions.v5.models.AutoValue_DirectionsError.<init>(AutoValue_DirectionsError.java:14) 
     at com.mapbox.directions.v5.models.AutoValue_DirectionsError$GsonTypeAdapter.read(AutoValue_DirectionsError.java:73)
     at com.mapbox.directions.v5.models.AutoValue_DirectionsError$GsonTypeAdapter.read(AutoValue_DirectionsError.java:17)
     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
     at com.mapbox.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:156)
```

cc @cammace

**Comment by kunalsharma** [comment]
Facing the same issue are you able to find solution ?

**Comment by cammace** [comment]
Can you guys provide the directions request builder which is being used to make the request? Having trouble getting this error message although I believe I know where it's coming from.

**Comment by cammace** [comment]
Added a few test and the handling of this is now improved. going ahead and closing.
