### ISSUE TITLE
NPE when building RouteOptions

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#708]
`null` value is passed into the `RouteOptions` Builder `requestUuid` intermittently when making requests. 

It looks like this might only be happening with `alternatives` set to true + the route request is for a longer route.

```
  java.lang.NullPointerException: Null requestUuid
      at com.mapbox.api.directions.v5.models.$AutoValue_RouteOptions$Builder.requestUuid($AutoValue_RouteOptions.java:353)
      at com.mapbox.api.directions.v5.MapboxDirections.generateRouteOptions(MapboxDirections.java:212)
      at com.mapbox.api.directions.v5.MapboxDirections.access$100(MapboxDirections.java:60)
      at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:165)
      at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
      at android.os.Handler.handleCallback(Handler.java:751)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6682)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
  ```

**Comment by osana** [comment]
This must be happening in https://github.com/mapbox/mapbox-java/blob/c16e72b63ba099874df4e237a6d474b52f0bf582/services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java#L212

**Comment by danesfeder** [comment]
Fixed by the directions team - the UUID should always have a value now
