### ISSUE TITLE
Update OkHttp to 3.10.0 for old telem library

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#726]
OkHttp 3.10.0 introduces a breaking change to the telemetry library found in this repo under the `mas-2.x.x` release. When updating to OkHttp in the 5.x series of the maps SDK, you will hit:

```
   java.lang.NoSuchMethodError: No static method toHumanReadableAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/-1/base.apk:classes8.dex)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.setUserAgent(MapboxTelemetry.java:315)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:174)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:125)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
        at com.company.MyApplication.onCreate(MyApplication.java:125)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

To be able to keep on serving our users with the 5.x series we should:
 - [x] update telemetry module to use OkHttp 3.10.0 
 - [x] replace the Lokhttp3/internal/Util/toHumanReadableAscii with an own implementaton
 - [x] release a new version of the telemetry library

@cammace would you be able to run with this? Would love to include this in the downstream 5.5.0 release of the maps sdk aimed to be released this week.

**Comment by tobrun** [comment]
Refs https://github.com/mapbox/mapbox-gl-native/issues/11325

**Comment by cammace** [comment]
Okhttp has been fixed, tracking the release in https://github.com/mapbox/mapbox-java/issues/728
