### ISSUE TITLE
MapboxDirections: Unable to place request on backend

### ISSUE THREAD

**Issue by msimpson** [mapbox/mapbox-java#857]
I seem unable to actually place a request using `MapboxDirections`. Regardless of the options used, I continually receive `Unable to place request on backend`. The code in question is minimal and otherwise should work. Also, note that a `MapView` is also present and performs just fine with the API key in question. I've already spent hours attempting to debug this issue, rummaging through Stack, so I'm coming here in a bid to save myself more time. Example code included below.

**build.gradle**
```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId "com.alextom.tour"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0-alpha3'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:3.3.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

**MainActivity.kt**
```
package com.alextom.tour

import android.support.v7.app.AppCompatActivity
import android.os.Bundle

import com.mapbox.geojson.Point

import com.mapbox.mapboxsdk.Mapbox
import com.mapbox.mapboxsdk.maps.MapboxMap
import com.mapbox.mapboxsdk.constants.Style
import com.mapbox.mapboxsdk.maps.MapView

import com.mapbox.api.directions.v5.MapboxDirections
import com.mapbox.api.directions.v5.DirectionsCriteria
import com.mapbox.api.directions.v5.models.DirectionsRoute
import com.mapbox.api.directions.v5.models.DirectionsResponse

import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response

import timber.log.Timber

class MainActivity : AppCompatActivity() {

    private lateinit var mapView: MapView
    private lateinit var map: MapboxMap

    private fun getRoute( origin: Point, destination: Point ) {
        MapboxDirections.builder()
                .accessToken( Mapbox.getAccessToken()!! )
                .origin( origin )
                .destination( destination )
                .overview( DirectionsCriteria.OVERVIEW_FULL )
                .profile( DirectionsCriteria.PROFILE_WALKING )
                .build()
                .enqueueCall( object: Callback<DirectionsResponse> {
                    override fun onResponse( call: Call<DirectionsResponse>, response: Response<DirectionsResponse> ) {
                        if ( response.body() == null ) {
                            Timber.e( "No routes found, make sure you set the right user and access token." )
                            return
                        }
                        else if ( response.body()!!.routes().size < 1 ) {
                            Timber.e( "No routes found." )
                            return
                        }
                        drawRoute( response.body()!!.routes()[ 0 ] )
                    }
                    override fun onFailure( call: Call<DirectionsResponse>, t: Throwable ) {
                        Timber.e( t )
                    }
                } )
    }

    private fun drawRoute( route: DirectionsRoute ) {
        // Stub
    }

    override fun onCreate( savedInstanceState: Bundle? ) {
        super.onCreate( savedInstanceState )

        Timber.plant( Timber.DebugTree() )

        Mapbox.getInstance( applicationContext, getString( R.string.mapbox_access_token ) )
        setContentView( R.layout.activity_main )

        val origin = Point.fromLngLat( 39.277161,-76.5674749 )
        val destination = Point.fromLngLat( 39.2772057,-76.5665354 )

        mapView = findViewById( R.id.mapView )
        mapView.onCreate( savedInstanceState )
        mapView.getMapAsync {
            map = it
            map.setStyle( Style.LIGHT )
            getRoute( origin, destination )
        }
    }

    override fun onStart() {
        super.onStart()
        mapView.onStart()
    }

    override fun onResume() {
        super.onResume()
        mapView.onResume()
    }

    override fun onPause() {
        super.onPause()
        mapView.onPause()
    }

    override fun onStop() {
        super.onStop()
        mapView.onStop()
    }

    override fun onSaveInstanceState( outState: Bundle ) {
        super.onSaveInstanceState( outState )
        mapView.onSaveInstanceState( outState )
    }

    override fun onLowMemory() {
        super.onLowMemory()
        mapView.onLowMemory()
    }

    override fun onDestroy() {
        super.onDestroy()
        mapView.onDestroy()
    }
}
```
**activity_main.xml**
```
<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:mapbox_cameraTargetLat="39.2776293"
        mapbox:mapbox_cameraTargetLng="-76.567075"
        mapbox:mapbox_styleUrl="mapbox://styles/mapbox/light-v9"
        mapbox:mapbox_cameraZoom="15" />

</RelativeLayout>
```
**Logcat**
```
07-26 10:10:06.652 3140-3140/com.alextom.tour E/MainActivity$getRoute: java.lang.Throwable: Unable to place request on backend
        at com.mapbox.api.directions.v5.MapboxDirections.errorDidOccur(MapboxDirections.java:192)
        at com.mapbox.api.directions.v5.MapboxDirections.access$000(MapboxDirections.java:60)
        at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:146)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
The error is coming from the ```onFailure``` of the ```DirectionsResponse``` callback.

**Comment by msimpson** [comment]
Well, ironically, I just solved the issue myself. It seems I had the latitude and longitude reversed the whole time:

```
val origin = Point.fromLngLat( 39.277161,-76.5674749 )
val destination = Point.fromLngLat( 39.2772057,-76.5665354 )
```

Should have been:

```
val origin = Point.fromLngLat( -76.5674749, 39.277161 )
val destination = Point.fromLngLat( -76.5665354, 39.2772057 )
```

However, it's quite unnerving that the error provided alluded to a connectivity issue rather than a coordinate issue...
