### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError in large MapMatching GET request

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#893]
_Originally opened in Navigation SDK_:  https://github.com/mapbox/mapbox-navigation-android/issues/1316

This seems to be some sort of error occurring when trying to make a MapMatching request.  Maybe the requests are very big?  @Danny-James, would you be able to provide more insight into the size of these MapMatching requests you're making?  Thanks! 

cc @osana 

**Error 1** - Motorola TC55 - Android 4.1.2 - http://crashes.to/s/691dcd1f232
```
Fatal Exception: java.lang.OutOfMemoryError
       at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
       at java.lang.StringBuilder.append(StringBuilder.java:124)
       at okhttp3.HttpUrl$Builder.toString(HttpUrl.java:1291)
       at okhttp3.HttpUrl.<init>(HttpUrl.java:351)
       at okhttp3.HttpUrl$Builder.build(HttpUrl.java:1256)
       at retrofit2.RequestBuilder.build(RequestBuilder.java:193)
       at retrofit2.ServiceMethod.toCall(ServiceMethod.java:113)
       at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
       at retrofit2.OkHttpCall.enqueue(OkHttpCall.java:95)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.enqueue(ExecutorCallAdapterFactory.java:62)
       at com.mapbox.api.matching.v5.MapboxMapMatching.enqueueCall(MapboxMapMatching.java:142)
       at uk.co.ainscough.routeinfo.ActivityNavigation.fetchRoute(ActivityNavigation.java:580)
       at uk.co.ainscough.routeinfo.ActivityNavigation.access$700(ActivityNavigation.java:57)
       at uk.co.ainscough.routeinfo.ActivityNavigation$1.onResponse(ActivityNavigation.java:621)
       at com.mapbox.api.matching.v5.MapboxMapMatching$1.onResponse(MapboxMapMatching.java:152)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4895)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Error 2** - Samsung SM-A320FL - Android 7.0 - http://crashes.to/s/646450c6cc2
```
Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:731)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
       at okhttp3.ConnectionPool.put(ConnectionPool.java:153)
       at okhttp3.OkHttpClient$1.put(OkHttpClient.java:163)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:266)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

I can see the mention of MapBox `MapMatching` in the first error, and assume the second error may be something with Mapbox as I don't believe i'm using `okhttp3` anywhere in my project.

**Comment by Danny-James** [comment]
@danesfeder I'm making lots of `MapMatching` Requests, I have a KML File which could contain around `9000+ Coordinates`, I have to split this up into sets of `100 Coordinates` and then make the `MapMatching` Requests once that directions route has completed I then request the next 100 in the `onArrival();` method, and so on until i have no coordinates left.

I have read online that this can happen when a new thread is opened for every request and it's best to use the same thread for all the requests, not sure whether this helps you in anyway.

**Comment by Danny-James** [comment]
@danesfeder I'm not sure what the cause of this error was but i've noticed another crash with OutOfMemoryError - http://crashes.to/s/023e00d0f96

**Comment by Danny-James** [comment]
Issue Present on New Device - `CAT S41` Device.

`CAT S41` Specs - https://www.gsmarena.com/cat_s41-8848.php

```
Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:730)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
       at okhttp3.Dispatcher.enqueue(Dispatcher.java:132)
       at okhttp3.RealCall.enqueue(RealCall.java:100)
       at retrofit2.OkHttpCall.enqueue(OkHttpCall.java:112)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.enqueue(ExecutorCallAdapterFactory.java:62)
       at com.mapbox.api.matching.v5.MapboxMapMatching.enqueueCall(MapboxMapMatching.java:142)
       at uk.co.ainscough.routeinfo.ActivityNavigation.fetchRoute(ActivityNavigation.java:622)
       at uk.co.ainscough.routeinfo.ActivityNavigation.access$800(ActivityNavigation.java:57)
       at uk.co.ainscough.routeinfo.ActivityNavigation$1.onResponse(ActivityNavigation.java:670)
       at com.mapbox.api.matching.v5.MapboxMapMatching$1.onResponse(MapboxMapMatching.java:152)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6255)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by Danny-James** [comment]
@danesfeder is their an update on this or anybody else I need to speak too?

**Comment by Danny-James** [comment]
@danesfeder @osana  Any chance of having someone look into this?

**Comment by Danny-James** [comment]
@danesfeder @osana Is their any chance somebody could reply to this issue? - We are unable to release our application due to this issue and no one seems to have acknowledged the issue as of yet.

**Comment by osana** [comment]
@Danny-James So far we could not reproduce it. It would help us a lot if you could provide us with a test case . Thank you

**Comment by Danny-James** [comment]
@osana, this is random - when using the MapMatching request i pass in 100 coordinates, once the user reaches the 85th coordinate i then remove the 85 coordinates which have passed and pass in another 85 coordinates, this continues until all the coordinates have been used.

I initially thought this was an issue with the Low Spec Motorla TC55 Devices, however this has also happened with Samsung Galaxy S8, CAT S41.

[Spec Sheet - TC55](https://www.zebra.com/us/en/products/spec-sheets/mobile-computers/handheld/tc55.html)

[Spec Sheet - CAT S41](https://images-eu.ssl-images-amazon.com/images/I/B1q1x9Q9iMS.pdf)

[Spec Sheet - Samsung Galaxy S8](https://www.samsung.com/global/galaxy/galaxy-s8/specs/)

With this out of memory issue happening with one of the most powerfull smartphones available I've come to the conclusion the device is not the issue.

**Comment by Danny-James** [comment]
Could this be because of the sheer amount of request being made? is their anyway I could use the same HTTP Connection for each `MapMatching Request` rather than creating a new connection every time, or is this how it already works?

**Comment by Danny-James** [comment]
@osana Any update on this? - This error is preventing the release of our application.

**Comment by shahzaib-ch** [comment]
@Danny-James I am facing this issue. It occurs when you keep activity with mapview open for a while keep interacting with it. If you see in profiler, something keeps eating memory and crashes with out of memory exception.
Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by osana** [comment]
@shahzaib-ch could you give more info on how you are interacting with the mapview. Any chance to get a simple test case where this is happening?

**Comment by shahzaib-ch** [comment]
I have mapview on multiple screens but it crashes only on screen where mapview covers whole screen. By interacting I mean to continuously scroll map.

**Comment by osana** [comment]
@shahzaib-ch your error suggests that there is some sort of data download apart from mapview scrolling.  It would be very very helpful if you could give a test case for it.

**Comment by Danny-James** [comment]
@osana Do we have any update on this issue?

**Comment by Danny-James** [comment]
@osana @danesfeder is their anything being done with this logged issue? - I've heard nothing since 3rd December 2018.

This error is preventing our company releasing our application.

**Comment by danesfeder** [comment]
@shahzaib-ch Your log doesn't seem to indication `MapMatching` usage as shown in this original issue.  Please open a new ticket with logs and a reproducible code snippet for the team to assess.  

@Danny-James I'm wondering if https://github.com/mapbox/mapbox-java/blob/master/services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java#L271-L280 will help you here.  This crash seems to occur when building the URL with the large amount of coordinates your adding to the request.  Can you retest with POST?  Thanks!

**Comment by Danny-James** [comment]
@danesfeder what is the correct usage of this please do you have an example of a MapMatching Post Request?

**Comment by devotaaabel** [comment]
@Danny-James you would add `builder.post()` to your `MapboxMapMatching` builder. Please give this a try and let me know if this helps.
