### ISSUE TITLE
mapbox navigation crashes

### ISSUE THREAD

**Issue by saikiran96** [mapbox/mapbox-java#960]
E/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager.<init>(AnnotationManager.java:87)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:79)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:56)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:44)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeNavigationSymbolManager(NavigationMapboxMap.java:583)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:92)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMap(NavigationView.java:556)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.access$100(NavigationView.java:68)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:222)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:839)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:204)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1176)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1040)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: ����������.
        at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager.<init>(AnnotationManager.java:87) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:79) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:56) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:44) 
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeNavigationSymbolManager(NavigationMapboxMap.java:583) 
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:92) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMap(NavigationView.java:556) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.access$100(NavigationView.java:68) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:222) 
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:839) 
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:204) 
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1176) 
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194) 
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1040) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:325) 
        at android.os.Looper.loop(Looper.java:142) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 13675 (ocator_forblind), pid 13675 (ocator_forblind)

this was the error
i followed the tutorail given in the ooficial website
https://docs.mapbox.com/help/tutorials/android-navigation-sdk/#next-steps

everything was working fine excpet for the last part

**Comment by TNT0305** [comment]
I am getting this exact error, too.  I'm using 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.32.0' with the "mapbox to the white house" trip from the example.  I started a new android project, set up the gradle as per the docs, made an mapbox_access_token string resource with my access token, and my MainActivity file is as follows:

```
package com.promiles.promilespermit;

import android.app.Activity;
import android.content.Context;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import com.mapbox.api.directions.v5.DirectionsCriteria;
import com.mapbox.api.directions.v5.models.DirectionsResponse;
import com.mapbox.api.directions.v5.models.DirectionsRoute;
import com.mapbox.geojson.Point;
import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncher;
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncherOptions;
import com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation;
import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute;

import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class MainActivity extends AppCompatActivity {

    DirectionsRoute myRoute;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button simulateBtn = this.findViewById(R.id.startSimulationButton);
        simulateBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                startTrip(true);
            }
        });
        String accessToken = getResources().getString(R.string.mapbox_access_token);
        Mapbox.getInstance(this, accessToken);
        // From Mapbox to The White House
        Point origin = Point.fromLngLat(-77.03613, 38.90992);
        Point destination = Point.fromLngLat(-77.0365, 38.8977);

        NavigationRoute.builder(this)
                .accessToken(accessToken)
                .origin(origin)
                .destination(destination)
                .build()
                .getRoute(new Callback<DirectionsResponse>() {
                    @Override
                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                        myRoute = response.body().routes().get(0);
                    }

                    @Override
                    public void onFailure(Call<DirectionsResponse> call, Throwable t) {

                    }
                });
    }
    private void startTrip(boolean shouldSimulate)
    {
        String accessToken = getResources().getString(R.string.mapbox_access_token);

        boolean simulateRoute = true;

        // Create a NavigationLauncherOptions object to package everything together
        NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                .directionsRoute(myRoute)
                .shouldSimulateRoute(simulateRoute)
                .build();

// Call this method with Context from within an Activity
        NavigationLauncher.startNavigation(this, options);
        return;
    }

}
```
The exact error I'm getting (from logcat):
```
2019-03-15 10:48:51.702 5225-5225/com.promiles.promilespermit E/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager.<init>(AnnotationManager.java:88)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:79)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:56)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:44)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeNavigationSymbolManager(NavigationMapboxMap.java:583)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:92)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMap(NavigationView.java:557)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.access$100(NavigationView.java:68)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:223)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:846)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:204)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1176)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1040)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager.<init>(AnnotationManager.java:88) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:79) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:56) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:44) 
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeNavigationSymbolManager(NavigationMapboxMap.java:583) 
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:92) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMap(NavigationView.java:557) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.access$100(NavigationView.java:68) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:223) 
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:846) 
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:204) 
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1176) 
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194) 
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1040) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:326) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    ```
The error makes me think its just not finding the "addOnWillStartLoadingMapListener" on the mapView.  But, I tracked through the definitions and the source Android Studio brought me to had that method.
Is there some dependency I'm missing?
Side note, I tried it with navigation-ui 0.27 and it works!  Trying it on 0.28, I get this error again.

**Comment by danesfeder** [comment]
Hey @saikiran96 👋 adding `JAVA_8` support to your project should resolve this:

`build.gradle`:

```
android {
  compileSdkVersion androidVersions.compileSdkVersion
  buildToolsVersion androidVersions.buildToolsVersion

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
...
}
```

If this doesn't resolve your issue, please open a new ticket in https://github.com/mapbox/mapbox-navigation-android/issues.  Thank you!

**Comment by TNT0305** [comment]
That got it, thanks!
